# Generated by Django 5.2.6 on 2025-09-15 18:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombre(s)')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=100, verbose_name='Apellido materno')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('alias', models.CharField(blank=True, max_length=100, verbose_name='Alias')),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Fotografía')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea1', models.CharField(max_length=150, verbose_name='Calle y número')),
                ('linea2', models.CharField(blank=True, max_length=150, verbose_name='Colonia / Depto.')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('estado', models.CharField(blank=True, max_length=100, verbose_name='Estado')),
                ('cp', models.CharField(blank=True, max_length=20, verbose_name='C.P.')),
                ('pais', models.CharField(blank=True, max_length=100, verbose_name='País')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='crud_personas.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Correo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correos', to='crud_personas.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=50, verbose_name='Etiqueta')),
                ('numero', models.CharField(max_length=30, verbose_name='Teléfono')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='crud_personas.persona')),
            ],
        ),
    ]
